name: Create Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    uses: vantage6/vantage6-workflows/.github/workflows/algorithm-release.yml@8e9e38e64d2937a67e355d731a79c799c598dfe6
    secrets: inherit
