name: Create Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    uses: vantage6/vantage6-workflows/.github/workflows/algorithm-release.yml@5eeeb059a46bdf29ec62936d1c4b58403ac8bf1e
    secrets: inherit
    with:
      docker_image: ghcr.io/vantage6/algorithm/session-basics
